### PR TITLE
Add option to connect to UNIX socket

### PR DESCRIPTION
**Pull request by ricklupton**
I wanted to connect to mysqld via a UNIX socket rather than IP, so I added an option. Hope this looks ok.

### CODE REVIEW

**Comment by techouse** [comment]
Hi!

Thanks for the PR!!!

I've added some comments. Please resolve them.

Also, some tests using a socket would be nice :)

**Comment by techouse** [comment]
@ricklupton can you please resolve the comments above?

**Comment by ricklupton** [comment]
@techouse sorry for not responding to your comments!

I'm not working on this at the moment and don't have a local mysql database set up for testing at the moment. If it comes up again that I need this I'd be happy to try to add tests then but I'm afraid I don't have time at the moment.

If you want to complete this yourself and/or close it until/if I can look at it, please go ahead.

**Comment by techouse** [comment]
I'm closing this then. Feel free to reopen when you have time again.

**Pull request closed without merging**
